### PR TITLE
sign assembly with strong name

### PR DESCRIPTION
**Pull request by bormm**
Dear Soroush,

it would be great if you would merge this request of adding a strong name to this assembly.
I also would be thankful for a new release on nuget.org with that change.

It would not harm any other user, but allows using this assembly in other assemblies and applications that already have a strong name and so need also every used assembly have a strong name.
I will also do a pull request for the WinFormAnimation.

Here you can find some information about strong naming in the dotnet project
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

### CODE REVIEW

**Comment by bormm** [comment]
Hi @falahati , 
have you any idea if you will and when you will merge this and publish a new nuget package? I have to know this, because if it will not happen within the next days, I have to switch to an other solution.
Thank you!

**Comment by falahati** [comment]
Hey,
This will be added soon. Today or tomorrow.

**Comment by falahati** [comment]
And thanks for the suggestion

**Comment by falahati** [comment]
The latest release is signed and is available here:
https://www.nuget.org/packages/CircularProgressBar/2.7.0.7

**Pull request merged**
